### ISSUE TITLE
Consume in .net Application

### ISSUE THREAD

**Issue by lahori007** [cyhex/streamcrab#17]
Hi,
I want to consume it .net application. I just want a function to which i give a string and it returns me score or positive/negative result.

thanks

**Comment by cyhex** [comment]
By design that was not included. However you have 2 options:
Option 1:
Extend the http server and include API for handling external requests
For example see https://github.com/cyhex/streamcrab/blob/master/smm/classifier/worker.py - this is where the actual classification taking place before it saved to mongodb.  

Option 2:
run a .Net app ( or in any other language ) that can access internal Queue messages of streamcrab stack. All messages (text input and classified text ) are saved in mongoDB  see:
https://github.com/cyhex/streamcrab/blob/master/smm/models.py ClassifiedStream line 31

It is somewhat a hack but it might work - just add record to RawStreamQueue table and it should be moved by streamcrab classifier to ClassifiedStream with classification, from there you can just read the data from .net

hope it helps
