### ISSUE TITLE
tweets_positive_test.dat & tweets_negative_test.dat

### ISSUE THREAD

**Issue by FGRibreau** [cyhex/streamcrab#7]
Hi,

I would like to quickly try out _smm_ but I can't due to these two missing data files:

``` Python
tweetsPFile = "/home/gx/Sites/SMM/trunk/tracker/data/tweets_positive_test.dat"
tweetsNFile = "/home/gx/Sites/SMM/trunk/tracker/data/tweets_negative_test.dat"
```

Did you generate them yourself ? If so, is it possible to commit them too ?

Thanks !

**Comment by cyhex** [comment]
hi, you have to generate them yourself...

**Comment by FGRibreau** [comment]
Why can't you commit them ? (I'm just curious)

**Comment by cyhex** [comment]
Because i do not have them any longer...

On Thu, 2011-12-22 at 12:11 -0800, Francois-Guillaume Ribreau wrote:

> Why can't you commit them ? (I'm just curious)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/cyhex/smm/issues/7#issuecomment-3254200

## 

Mit freundlichen Grüßen / Kind Regards,

Timor A.
cyHex - Logical Solutions

timor@cyhex.com
+493051643600
+491632301182
www.cyhex.com

---

The information contained in this message is proprietary of cyHex,
protected from disclosure, and may be privileged.
The information is intended to be conveyed only to the designated
recipient(s) of the message. If the reader of this message is not
the intended recipient, you are hereby notified that any
dissemination, use, distribution or copying of this communication
is strictly prohibited and may be unlawful.
If you have received this communication in error, please notify us
immediately by replying to the message and deleting it from your
computer.
Thank you.

**Comment by suhas-p-bharadwaj** [comment]
Hi,

Can you please suggest how to build a better data set ? Other than the smileys what can be done so that the accuracy can increase ?

**Comment by FGRibreau** [comment]
@suhas-p-bharadwaj If you succeed, could you please share your data ? 
Thanks a lot !

**Comment by cyhex** [comment]
due to some requests i extended my README to Hot to build your own dataset, How to test your own datasets
check it out, perhaps it would be helpful.
https://github.com/cyhex/smm/blob/master/README.md

Timor

**Comment by suhas-p-bharadwaj** [comment]
@cyhex : Thanks a lot!!
